sudo: required
dist: xenial
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
env:
  global:
  - BUILDKIT_HOST=tcp://0.0.0.0:1234
  - DOCKER_CLI_EXPERIMENTAL=enabled
  matrix:
  - secure: JE0oM2BwXxlJXAedQCA7HSqq2jp+JVTVgZ/+u2KItEsd5ts3SK+zpCiJB+8kgt/0XCMfVR/0ijIQ8Dfet9G5cuLvMgVmZ0KixQIK1qNO419HDWhvwexvAViuplG67kzDdAIoo0ce3rXU2f+bOtR/qZdUFM+n8/xbIOXeMpsJMoEFE30VlMuKGN8GxwWEuIQEW31/rLatK9k7LMYUmyVUjLFAkyA3euE79dRsi9NmU2bSEsMDlhQ37M0xujEm8donW5Dy5EKR88/Dwnkw8os4VlItA26z9vL0kHc3w5FDrOVJclaSrEKqulCFNrrFKlJV3klc3HJx7EveErUuPfod6Pq/ZMh4sPpHCSD5uEWKc68Psq25/M89o/TOHUnPrDNuh4FqB4yh9ZECCSekJhOjSuTPWmpBel0gyFFABI8GYHgWa3KZYFSlznpTe+j70mUHWmOn4ENyQieMqhj70WTsL6AIBoDThGVi7l/Vco6cwlaxMgapVJAxERTobMIS06vj+l1Fr/tCrsQnO5CiNhk4Te+pVKxRt8dMqF8XI3QgZzRRwbMgyV6Crx/OTITz+vyvYqsRZa4+nv6ohfFTRR+JgkRGO21LzM70H8aqpsWm50Fp7enzg61fg6t8yKVux4/7OgAnsIdik8/SWamneQa2wfBkRksdwse7I1bQaOCuTN8=
  - secure: XJkZIENDd8TqQAet3XyPXnyG8arl6gbI4pYWvQi9MoHG4iCiGW4sBfn+DBr1kVfB3ee5t+rGt8dvaWAmUZEZY0K8zVXldQaNQiT6kyd+vSjDUCh0me+ykz2Y7sroDSNowcxdy1MMVntz2kmLxShKgERoprjVeZ95Z0eL+YQMGzcI4bSynm1caWOybT+L8m+cgb/2DHyvrdrfgVFL6aVkSkjAlaeAS4H7Ewun1zOhNba6H8CjI/csDrMk3VJSBjYblInRNvPQAsSiAopmnwT3GIlEfTvp6QqRwl9YrzfPvcgg42GPDx8VmewQDMtyHQEOU9/P2XtQOLwwMrfm8GXD8DERBerBkerJ0CIRQN/OzirTYRyZeo8jdB6ycH264kmQ22+PjbOoJVoopW3DJbEFoaAlqSH/1/WnRda2mD2WQYy0JiBif3Ksa2gk/nsOSCu2LljiKB7NMLBVkD7qfgObq5UMZXwCFwtZ2dsdYPOWP3YNT2Djs9W2NcgsZgYDAU0GH2di/MT5mEFkmsWxGwhZvhuXQm50oHuKw9zPU2k6dWzGjdVzzjgo40Oxk7mdYH49vYyk0ZN7eYWxxaR6b6+yk1+UGzTc7epuZ4tw9iu2FBNqcB87AjCp+cPjKYFuO2O3/I3Q+RgluXTCCNGp7D6QKzkOXLpMIP2eyDPF5pp8SYE=

after_failure:
- tail --lines=500 build.log

jobs:
  include:
  - stage: build and push SMUI docker image
    script:
    - echo '{"experimental":true}' | sudo tee /etc/docker/daemon.json
    - sudo service docker restart
    - touch build.log
    - while sleep 30s; do tail --lines=50 build.log; done &
    - time make docker-build > build.log 2>&1
    - kill %1
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - sudo make docker-push
