sudo: required
dist: xenial

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

env:
  global:
    - BUILDKIT_HOST=tcp://0.0.0.0:1234
    - DOCKER_CLI_EXPERIMENTAL=enabled

jobs:
  include:
    - stage: build and push SMUI docker image
      script:
        - sudo make docker-build
        - sudo make docker-push
